#docker-compose.yml file
#-----------------------
version: "3"
services:
  test_controller:
    build: . # Path to the Dockerfile
    image: controller
    container_name: lb
    ports:
      - "5000:5000" # Exposing port to host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    # This share host’s the docker daemon with the container. Now, the container can spawn other containers just like host
    privileged: true # This should be true to share the docker daemon
    networks:
      - myNetwork # Need to define net1 in the compose file
    # aliases:
      # - test_lb_container # Usually same as containername
    environment:
      - N=3 # Environment variables accessed with os.environ['N'].

networks:
  myNetwork: {}